// Package aws implements the AWS provider: offline evaluation of policy
// documents, live collection through the IAM and Organizations APIs, and
// the Terraform plan adapter.
package aws

import (
	_ "embed"
	"fmt"
	"sync"

	"github.com/IbiliAze/iamdiff/internal/catalogue"
	"github.com/IbiliAze/iamdiff/internal/model"
	"github.com/IbiliAze/iamdiff/internal/provider"
)

// The embedded snapshot is regenerated by scripts/gen-catalogue-aws.sh.
//
//go:embed data/catalogue.json
var catalogueData []byte

// embeddedCatalogue parses the snapshot once per process: it holds
// twenty thousand actions and every command opens the provider.
var embeddedCatalogue = sync.OnceValues(func() (*catalogue.Static, error) {
	return catalogue.Load(catalogueData)
})

const Name = "aws"

func init() {
	provider.Register(Name, New)
}

type Provider struct {
	cfg provider.Config
	cat catalogue.Catalogue
}

func New(cfg provider.Config) (provider.Provider, error) {
	cat, err := embeddedCatalogue()
	if err != nil {
		return nil, fmt.Errorf("aws: load catalogue: %w", err)
	}
	return newWithCatalogue(cfg, cat), nil
}

// newWithCatalogue lets tests pin a small, stable catalogue so that
// assertions about expansion counts do not float with the weekly refresh.
func newWithCatalogue(cfg provider.Config, cat catalogue.Catalogue) *Provider {
	return &Provider{cfg: cfg, cat: cat}
}

func (p *Provider) Name() string                   { return Name }
func (p *Provider) Catalogue() catalogue.Catalogue { return p.cat }

// FromDocuments builds a RawSet with no credentials. This is what powers
// `iamdiff policy a.json b.json`.
func (p *Provider) FromDocuments(pr model.Principal, docs []provider.Document) (*provider.RawSet, error) {
	pr.Provider = Name
	return &provider.RawSet{Principal: pr, Documents: docs}, nil
}

var (
	_ provider.Provider      = (*Provider)(nil)
	_ provider.Cataloguer    = (*Provider)(nil)
	_ provider.Explainer     = (*Provider)(nil)
	_ provider.OfflineLoader = (*Provider)(nil)
)
